version: '2.1'
services:
  events-bot:
      container_name: eventsbot
      image: cloud.canister.io:5000/mplacona/events-bot
      environment:
        HAWKEYE_USERNAME: ${HAWKEYE_USERNAME}
        HAWKEYE_PASSWORD: ${HAWKEYE_PASSWORD}
      ports:
        - "8081:8888"